id: 6a5b03596d7a4bb28d0a506901be6862
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_54-The_Exposition_on_the_Universal_Gateway-v2
  language: bo
  author: ''
  volume: {}
